# Generated by Django 5.1.2 on 2024-10-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.CharField(editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
