# Generated by Django 5.1.2 on 2024-10-24 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_foodreviews'),
        ('main', '0002_reply'),
    ]

    operations = [
    ]
