# Generated by Django 5.1.2 on 2024-10-20 09:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_food_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='id',
        ),
        migrations.AddField(
            model_name='food',
            name='food_id',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=36, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
