# Generated by Django 5.1.2 on 2024-10-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_food_id_food_food_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
