# Generated by Django 5.1.2 on 2024-10-26 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_food_user'),
        ('main', '0004_alter_food_user'),
    ]

    operations = [
    ]
