# Generated by Django 5.1.2 on 2024-10-25 08:56

import detail_makanan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_makanan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreviews',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=detail_makanan.models.upload_to),
        ),
    ]
